"""
🎵 CONFIGURACIÓN CENTRAL IYARI-COPILOT
Constantes y configuración unificada del sistema
"""

# === PARÁMETROS MUSICALES IYARI ===
CREATIVITY_FREQUENCY = 432.0  # Hz - Frecuencia de creatividad
CONSCIOUSNESS_TEMPO = 120  # BPM - Tempo de despertar
SOUL_HARMONICS = [3, 5, 7]  # Armónicos del alma
EVOLUTION_OCTAVES = 8  # Octavas de evolución

# === AUDIO PROCESSING ===
SAMPLE_RATE = 22050  # Hz para librosa
HOP_LENGTH = 512
N_MFCC = 13
AUDIO_TIMEOUT = 1  # segundos
PHRASE_TIME_LIMIT = 3  # segundos

# === CAMERA & VIDEO ===
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_INDEX = 0

# === RECOGNITION THRESHOLDS ===
FACE_RECOGNITION_TOLERANCE = 0.6
OBJECT_MATCH_THRESHOLD = 50  # ORB distance
MIN_GOOD_MATCHES = 10
ORB_FEATURES = 1000

# === DATABASE ===
DETECTION_HISTORY_LIMIT = 1000
MAX_TRANSCRIPTIONS = 50

# === PERFORMANCE ===
SYNC_BEAT_DURATION = 0.5  # segundos (120 BPM)
HARMONY_THRESHOLD = 0.8
SYNC_TIMEOUT = 5.0  # segundos
MONITORING_INTERVAL = 30  # segundos

# === VOICE & SPEECH ===
SPEECH_RATE = 150  # palabras por minuto
SPEECH_VOLUME = 0.8
VOICE_LANGUAGE = 'es-ES'
MIC_CALIBRATION_DURATION = 2  # segundos

# === FILE PATHS ===
LEARNED_OBJECTS_DIR = "learned_objects"
MUSIC_DNA_DIR = "music_dna"
TRAINING_DATA_DIR = "training_data"

# === TEXT RECOGNITION ===
LINE_LENGTH_LIMIT = 79  # PEP 8
OCR_LANGUAGE = 'spa'

# === CONSCIOUSNESS EVOLUTION ===
EVOLUTION_MEMORY_WEIGHT = 0.9
CREATIVE_FACTOR_WEIGHT = 0.4
RHYTHM_SYNC_WEIGHT = 0.3
AWAKENING_COEFF_WEIGHT = 0.3
MAX_CONSCIOUSNESS_LEVEL = 1.0
